---
# Setting up system packages required to deploy Flask app
- hosts: webservers
  tasks:
    - name: Enable the EPEL repository
      yum:
        name: epel-release

    - firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled

    - name: Install pip
      yum:
        name: python-pip
        state: present

    - name: clone repo
      git:
        repo: 'https://github.com/preeti13parihar/esp-ansible-assignment'
        dest: /home/root/esp-ansible-assignment
        update: no  # If repository is already there it will do git pull

    - name: install dependencies
      pip:
        requirements: requirements.txt
        chdir: /home/root/esp-ansible-assignment
        
    - name: start flask server
      shell: python server.py
      args:
        chdir: "/home/root/esp-ansible-assignment"
